# Generated by Django 2.2.5 on 2019-09-28 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190928_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='des',
            new_name='desc',
        ),
    ]
